/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_olf_requestcamaccess_Requestor */

#ifndef _Included_de_olf_requestcamaccess_Requestor
#define _Included_de_olf_requestcamaccess_Requestor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_olf_requestcamaccess_Requestor
 * Method:    RequestAccessImpl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_olf_requestcamaccess_Requestor_RequestAccessImpl
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
